baseURL = "https://it-in-family.github.io/"
title = "IT in Family"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"
   
[params]
   geekdocLogo = "logo.svg"
   geekdocMenuBundle = true
   geekdocRepo = "https://github.com/It-in-family/it-in-family.github.io"
   geekdocEditPath = "blob/main"
   geekdocCollapseAllSections = true
